export const jobs = [
  {
    id: 1,
    name: 'Sales Associate across Nigeria',
    role: 'Sales Associate',
    type: 'Full Time',
    location: 'Lagos',
    link: 'sales',
    subjectText: 'Job Application - Sales Associate across Nigeria',
  },
  {
    id: 2,
    name: 'Procurement Associate',
    role: 'Procurement Associate',
    type: 'Full Time',
    location: 'Lagos',
    link: 'procurement',
    subjectText: 'Job Application - Procurement Associate',
  },
  {
    id: 3,
    name: 'Executive Assistant to the Executive Office',
    role: 'Executive Assistant',
    type: 'Full Time',
    location: 'Lagos',
    link: 'executive',
    subjectText: 'Job Application - Executive Assistant to the Executive Office',
  },
  {
    id: 4,
    name: 'Quality Assurance Associate',
    role: 'Quality Assurance Associate',
    type: 'Full Time',
    location: 'Lagos',
    link: 'qa',
    subjectText: 'Job Application - Quality Assurance Associate',
  },
];
