import PrivacyMetadata from 'components/meta/privacy';
import styled from 'styled-components';

export default function TermsAndConditions() {
  return (
    <>
      <PrivacyMetadata />
      <Container>
        <div className="header">
          <div className="container">
            <Container>
              <div className="privacy-notice">
                <h1>PRIVACY NOTICE OF DRUGSTOC EHUB LIMITED</h1>

                <h2 style={{ fontSize: 24, fontWeight: 'bold' }}>
                  INTRODUCTION
                </h2>
                <p>
                  <strong>1.1</strong> Drugstoc Ehub Limited is a tech-based
                  pharmaceutical distribution Company incorporated under the
                  Laws of the Federal Republic of Nigeria.
                </p>
                <p>
                  <strong>1.2</strong> References in this notice to "we", "us"
                  or "Drugstoc" are references to Drugstoc Ehub Limited.
                </p>
                <p>
                  <strong>1.3</strong> Reference in this Notice to "personal
                  data" means any information that identifies, or could
                  reasonably be used to identify, a living individual, either on
                  its own or together with other information.
                </p>

                <h2 style={{ fontSize: 24, fontWeight: 'bold' }}>
                  WHAT INFORMATION WE COLLECT ABOUT YOU
                </h2>
                <ul style={{ marginLeft: 15 }}>
                  <li>
                    Basic information such as name, date of birth, employer,
                    title, relationship affiliations with a person or
                    organization.
                  </li>
                  <li>
                    Contact information such as physical address, email address,
                    fax, and phone number(s).
                  </li>
                  <li>
                    Background information provided by you or collected by us as
                    part of our recruitment or contract employee onboarding
                    processes.
                  </li>
                  <li>
                    Confidential information provided to us by or on behalf of
                    our clients or generated by us in the course of providing
                    our products/services.
                  </li>
                  <li>
                    Details relating to your visits to our offices or work
                    sites.
                  </li>
                  <li>
                    Any other information relating to you which you may provide
                    to us.
                  </li>
                </ul>

                <h2 style={{ fontSize: 24, fontWeight: 'bold' }}>
                  HOW WE PROTECT YOUR PERSONAL INFORMATION
                </h2>
                <p>
                  <strong>3.1</strong> We are committed to protecting your
                  personal information and implementing appropriate technical
                  and organizational security measures to protect it against any
                  unauthorized or unlawful processing and against any accidental
                  loss, destruction, or damage.
                </p>
                <p>
                  <strong>3.2</strong> Our IT security practices are contained
                  in our Information Security Policy.
                </p>

                <h2 style={{ fontSize: 24, fontWeight: 'bold' }}>
                  HOW WE USE YOUR PERSONAL DATA
                </h2>
                <p>
                  Whether we obtain your personal data directly from you or from
                  a third party, we will only use your personal data in
                  connection with our professional activities, legitimate
                  interests (including the fulfillment of our contractual or
                  legal/regulatory obligations). These "Authorized Uses"
                  include:
                </p>
                <ul style={{ marginLeft: 15 }}>
                  <li>Providing our professional services to our clients.</li>
                  <li>
                    Managing our business relationship with our service
                    providers and/or vendors.
                  </li>
                  <li>
                    Acting in compliance with our legal obligations or pursuant
                    to a valid court order.
                  </li>
                  <li>
                    In furtherance of or to protect the vital interest of the
                    data subject.
                  </li>
                  <li>
                    Processing your requests/information further to your consent
                    during your visit to our offices and online platforms.
                  </li>
                  <li>
                    Legitimate interests pursued by the Company or by a third
                    party to whom the data is disclosed.
                  </li>
                </ul>

                <h2 style={{ fontSize: 24, fontWeight: 'bold' }}>
                  HOW YOUR PERSONAL DATA IS OBTAINED
                </h2>
                <ul style={{ marginLeft: 15 }}>
                  <li>
                    In the course of our recruitment or employee onboarding
                    processes.
                  </li>
                  <li>
                    Further to an employment, service, or any other contractual
                    obligation we have with you.
                  </li>
                  <li>
                    When you email us, contact us via our website, or subscribe
                    to our services.
                  </li>
                  <li>When you physically visit any of our premises.</li>
                  <li>When you attend any of our event(s).</li>
                  <li>
                    When you volunteer your personal data to us for any specific
                    reason(s).
                  </li>
                </ul>

                <h2 style={{ fontSize: 24, fontWeight: 'bold' }}>
                  SHARING YOUR PERSONAL DATA
                </h2>
                <p>
                  Your personal data may be shared with our related entities and
                  affiliates. Where we share your personal data with third
                  parties, we will do this in accordance with the Nigerian Data
                  Protection Act, 2023 (NDPA) and NDPR observing appropriate
                  safeguards.
                </p>

                <h2 style={{ fontSize: 24, fontWeight: 'bold' }}>MARKETING</h2>
                <p>
                  We may send you information about our products, services, and
                  special offers which may be of interest to you. You can
                  unsubscribe at any time by contacting us at{' '}
                  <a href="mailto:info@drugstoc.com">info@drugstoc.com</a>.
                </p>

                <h2 style={{ fontSize: 24, fontWeight: 'bold' }}>
                  RETAINING YOUR PERSONAL DATA
                </h2>
                <p>
                  We will delete your personal data when it is no longer
                  required for the Authorized Uses, subject to our retention
                  policy.
                </p>

                <h2 style={{ fontSize: 24, fontWeight: 'bold' }}>
                  YOUR RIGHTS AS A DATA SUBJECT
                </h2>
                <ul style={{ marginLeft: 15 }}>
                  <li>
                    Right of access &mdash; You can request a copy of the
                    information we hold about you.
                  </li>
                  <li>
                    Right of rectification &mdash; You can correct inaccurate or
                    incomplete data.
                  </li>
                  <li>
                    Right to be forgotten &mdash; You can ask for your data to
                    be erased.
                  </li>
                  <li>
                    Right of portability &mdash; You can transfer your data to
                    another organization.
                  </li>
                  <li>
                    Right to object &mdash; You can object to certain types of
                    processing.
                  </li>
                </ul>

                <h2 style={{ fontSize: 24, fontWeight: 'bold' }}>CONTACT US</h2>
                <p>
                  <strong>Data Protection Officer:</strong> Cynthiamary Unaka
                </p>
                <p>
                  Email:{' '}
                  <a href="mailto:info@drugstoc.com">info@drugstoc.com</a>
                </p>
                <p>Telephone: 08036879999</p>

                <h2 style={{ fontSize: 24, fontWeight: 'bold' }}>
                  REVISION TO THIS PRIVACY NOTICE
                </h2>
                <p>
                  Drugstoc reserves the right to modify this Privacy Notice at
                  any time.
                </p>
              </div>
            </Container>
          </div>
        </div>
      </Container>
    </>
  );
}

const Container = styled.div`
  margin: 150px 0;
  h3 {
    text-align: center;
  }
  h4 {
    margin: 30px 0;
  }
  li li {
    margin-left: 50px;
    margin-top: 20px;
  }
  ul {
    margin-top: 20px;
    margin-bottom: 20px;
  }
  li {
    margin-top: 40px;
  }
  h6 {
    font-weight: bold;
  }
`;
